apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: helloworld
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
     app: helloworld
  replicas: 4
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: helloworld:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
